# Generated by Django 5.0.7 on 2024-07-28 21:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('origin_country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=14)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.CharField(choices=[('diesel', 'Diesel'), ('gasoline', 'Gasoline'), ('hybrid', 'Hybrid')], max_length=100)),
                ('gearbox', models.CharField(choices=[('automatique', 'Automatique'), ('manual', 'Manual')], max_length=100)),
                ('doors', models.IntegerField(validators=[django.core.validators.MinValueValidator(2)])),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)])),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cartype', models.CharField(choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('coupe', 'Coupe'), ('suv', 'Suv'), ('sport', 'Sport')], max_length=100)),
                ('mealage', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('hp', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('model', models.CharField(max_length=100)),
                ('seats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2)])),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.brand')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.garage')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('caption', models.CharField(max_length=500)),
                ('idcar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.car')),
            ],
        ),
    ]
