# Generated by Django 5.0.7 on 2024-07-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_car_hp_alter_car_mealage_alter_car_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
