# Generated by Django 5.0.7 on 2024-07-30 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_image_url_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='idcar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.car'),
        ),
    ]
