# Generated by Django 5.0.7 on 2024-07-30 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_image_idcar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='idcar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.car'),
        ),
    ]
