# Generated by Django 5.0.7 on 2024-07-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_garage_car_gar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='gar',
            new_name='garage',
        ),
    ]
